### ISSUE TITLE
 KY-011 Two-color

### ISSUE THREAD

**Issue by josue0620** [tectijuana/sensores#110]
![Two_Color_Titulo](https://user-images.githubusercontent.com/84551683/145327116-79def1df-23fd-4e3a-8442-721bd791d4f1.png)
![Two_Color_Portada](https://user-images.githubusercontent.com/84546168/145497453-dd7ff055-8ee3-4192-99b6-f96864b8c3ec.jpg)

**Comment by LuisDeJesusR** [comment]
# MARCO TEÓRICO
### ¿Qué es el LED Bicolor Módulo KY-011?
El LED Bicolor Módulo KY-011 consta de un LED cátodo común que esta conectado a leds  que emite una luz roja y verde, se puede ajustar la intensidad de color usando pulsos de ancho modulado (PWM) y utilizar 2 resistencias 330 Ω para limitar el voltaje y evitar que se dañe el dispositivo.

### ¿Cómo utilizar el Módulo KY-011?
Esté modulo KY-011 led bicolor lo puedes utilizar como luz indicadora en alguno de tus proyectos para mostrar Encendido (verde) y Apagado (rojo), o funcionamiento correcto e incorrecto. Es útil en aparatos como: MP3,  cámaras digitales, audio para automóviles, comunicaciones, computadoras, cargadores, instrumentación, regalos, juguetes electrónicos y teléfonos móviles. Este modulo es muy similar al KY-029.

**Comment by LuisDeJesusR** [comment]
# DIAGRAMAS
### Conexión
| KY-011 | Tablero | Pi Pico |
|--------|---------|---------|
| -      |         | Pin 38  |
| medio  | 330 Ω   | Pin 27  |
| S      | 330 Ω   | Pin 26  |

*Nota: se recomienda utilizar resistencias de 330 Ω*

![Two_Color_Diagrama](https://user-images.githubusercontent.com/84546168/145503065-5ba115b5-67c3-44bd-8c09-2cb447d27669.png)

**Comment by LuisDeJesusR** [comment]
# TABLAS TÉCNICAS
### Especificación y características
| Propiedad                 | Característica            |
|---------------------------|---------------------------|
| Tipo Led                  | bicolor cátodo común 5 mm |
| Voltaje de funcionamiento | 2 V a 2.5 V               |
| Corriente                 | 10mA                      |
| Angulo de visión          | 150°                      |
| Longitud de onda          | 571nm a 644 nm            |
| Intensidad luminosa       | 20-40 y 40-80 MCD         |
| Color                     | Rojo y Verde              |
| Dimensiones               | 40 mm ,15 mm y 7 mm       |
| Peso                      | 1 gr                      |

### Pines
![Two_Color_Pines](https://user-images.githubusercontent.com/84546168/145503126-82ce05f6-5393-460a-9118-7c28b8c63568.png)
| Pin del componente | Propiedad |
|--------------------|-----------|
| (-)                | GND       |
| medio              | rojo      |
| S                  | verde     |

**Comment by LuisDeJesusR** [comment]
# CÓDIGO
```python
#Cuevas Oliva Josue Emanuel 18212164

from machine import Pin
import time

led_pins=[21,20]#Pines de LEDS
leds=[Pin(led_pins[0],Pin.OUT),Pin(led_pins[1],Pin.OUT)]#Matriz de control de pines

while True:
    for led in leds:#Iteracion entre cada led
        led.high()#LED Encendido
        time.sleep(0.1)#Tiempo de espera
        led.low()#LED Apagado
        time.sleep(0.1)#Tiempo de espera
```

**Comment by LuisDeJesusR** [comment]
Link del repositorio:
https://github.com/tectijuana/sensores/tree/master/PYTHON/KY-011%20Two-color
