### ISSUE TITLE
KY-034 7 Color Flash

### ISSUE THREAD

**Issue by DanielAquinoIng** [tectijuana/sensores#111]
![KY-034-TITULO](https://user-images.githubusercontent.com/84304719/145503596-9a7de843-51c5-4f74-ab15-de43ead5a532.png)

### El módulo KY-034 Led Flash te permitirá generar una luz aleatoria muy intensa y de 7 colores de forma fácil y rápida

![KY-034](https://user-images.githubusercontent.com/84304719/145503611-69ae88a8-4865-495a-a8e0-d136352d22c3.png)

**Comment by FernandoChD** [comment]
## MARCO TEÓRICO

### Descripción
El Led Flash de 7 colores es útil para sistemas en donde se requiera algún tipo de señalización visual o decorativo, por ejemplo en maquinaria, juguetes, sistemas de control, por mencionar algunos.

**Comment by FernandoChD** [comment]
## MARCO TEÓRICO

### Descripción
El Led Flash de 7 colores es útil para sistemas en donde se requiera algún tipo de señalización visual o decorativo, por ejemplo en maquinaria, juguetes, sistemas de control, por mencionar algunos.

Este módulo de color cambiante está compuesto por un led emisor de luz de alto brillo y una resistencia limitadora de superficie para proteger el led. Dicho led es de 5 mm redondo con modelo del producto YB-3120B4PnYG-PM que posee una lente tipo “luz antiniebla blanco” y maneja un voltaje estándar de 3.0 – 4.5 volts, pero debido a la resistencia limitadora incluida funcionara perfectamente a 5 Volts.

**Comment by FernandoChD** [comment]
## DIAGRAMAS

* GND -----> Pin 3
* SEÑAL---> Pin 5


![KY-034-DIAGRAMA](https://user-images.githubusercontent.com/84304719/145511506-176d5e2d-adc7-4747-8db8-0acd0de6863c.png)


## TABLAS TÉCNICAS

### Especificaciones

* Voltaje de funcionamiento: 3 a 5 V
* Modelo del producto: YB-3120B4PnYG-PM
* Forma: Redondo Tipo de LED DIP 5mm
* Grupo de colores: verde, amarillo y rosa (alto brillo).
* Tipo de lente: niebla blanca
* Dimensiones: 19mm x 17mm x 20 mm
* Peso: 2 g


![KY-034-PINOUT](https://user-images.githubusercontent.com/84304719/145506729-b4cd8a28-ba36-43e8-b51e-8748817a4dc6.png)

**Comment by FernandoChD** [comment]
## CÓDIGO

```python
#Modulo KY-034 7 Color Flash en Raspberry Pi Pico
#Chavez Duarte Fernando

from machine import Pin
from utime import sleep

led = Pin(3,Pin.OUT)

while True:
        led.on()
        sleep(1)
        led.off() 
        sleep(1)

**Comment by Rulas-Boy** [comment]
Estoy teniendo inconvenientes para correr el código de este módulo.
Y no sabría distingir si es por error en la codificación, o porque está quemado mi sensor.
