### ISSUE TITLE
Sensor Infrarojo

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/sensores#115]
Circuitpython y hacer el archivo a ejecutar

**Comment by Rulas-Boy** [comment]
Me encuentro un poco ocupado profesor, @IoTeacher.
Iré directo a probar lo que comentó en Classroom en cuanto antes, aproximadamente en una hora.

**Comment by CesarAm233** [comment]
[![Sensor-Infrarrojo-Titulo.png](https://i.postimg.cc/ZnyD7FH9/Sensor-Infrarrojo-Titulo.png)](https://postimg.cc/RJ4Rqtj9)

**Comment by CesarAm233** [comment]
Un detector infrarrojo es un tipo de dispositivo que tiene la capacidad de medir la radiación electromagnética infrarroja que emiten los cuerpos que se encuentran dentro de su campo de visión. Se trata de un tipo de radiación que emiten todos los cuerpos de forma independiente a que exista otro tipo de luz ambiental. De este modo, permite observar espacios y objetos sin necesidad de que exista luz visible o de otro tipo en el entorno.

**Comment by CesarAm233** [comment]
[![Diagrama-Sensor-Infrarrojo.png](https://i.postimg.cc/XJ5zxkQr/Diagrama-Sensor-Infrarrojo.png)](https://postimg.cc/ftwCRm4s)

**Comment by CesarAm233** [comment]
|         Proyecto        |  Prueba en simulación  | 
|-----------------------|---------------|
|  Control remoto          | https://www.loom.com/share/c468d38a9b9e46b38c77648d3af020b6  |

**Comment by CesarAm233** [comment]
```python
#include <IRremote.h>
#define pinSensorIR 11

IRrecv sensorIR(pinSensorIR) ;
decode_results codigoIR;

void setup() {
	Serial.begin(9600);
	sensorIR.enableIRIn();
}

void loop () {
	if (sensorIR.decode(&codigoIR)) {
		Serial.println(codigoIR.value,HEX);
		sensorIR.resume () ;
	}
	delay (100);
}
```
