### ISSUE TITLE
Módulo Sensor de Sonido de micrófono

### ISSUE THREAD

**Issue by esdrasma** [tectijuana/sensores#14]

**Comment by esdrasma** [comment]
# Sensor de Sonido de Micrófono

![image](https://user-images.githubusercontent.com/60414177/76579032-fd39af00-6487-11ea-89dd-716ce1146fea.png)

## Información
Éste módulo permite la conexión de un micrófono Electret a los pines digitales de un microcontrolador. El nivel de detección acústico puede ser ajustado mediante un potenciómetro para sensar la intensidad del sonido.
El módulo cuenta con ganancia ajustable para el micrófono con el fin de obtener una mejor lectura, además cuenta con tres pines para conectarlo fácilmente a un Arduino, Microcontrolador o cualquier tarjeta de desarrollo.

## Características
* Módulo para detección de ruido. 
* Cuenta con micrófono Electret y sensibilidad de detección ajustable.
* Indica salida de señal.
* Salida de la señal de canal individual.
* La señal de salida es efectiva bajo nivel.

## Especificaciones Técnicas
* Tamaño: aprox. 32mm * 17mm * 15mm (largo * ancho * altura) 
* Principal Chip: LM393, micrófono de condensador Electret 
* Voltaje de funcionamiento: DC 4-6V 
* Color: Azul 
* Peso neto: 3g 
* Nota : La distancia máxima de la inducción es 0,5 M 

## Comparación de precios

Comercio | Precio 
------------ | ------------- |
![com1](https://www.geekfactory.mx/wp-content/uploads/2020/07/logo-geek-factory.png) | $21.00 | 
![com2](https://logodownload.org/wp-content/uploads/2018/10/mercado-libre-logo.png) | $46.00|
![com3](https://applealdoble.com/wp-content/uploads/2020/08/Amazon-logo.png) | $184.24

## Circuito 

![circuito1](http://www.iescamp.es/miarduino/wp-content/uploads/2016/02/lampara-aplausos_bb.png)

## Código

##### int volumen;

#####  void setup() {
#####   Serial.begin(9600);
##### }

##### void loop() {

#####   volumen = analogRead(A0); 
#####     Serial.println(volumen); 
#####         delay(50); 

##### }

**Comment by IoTeacher** [comment]
https://www.tinkercad.com/circuits
https://myopenlab.org/inicio/

`Void `
