### ISSUE TITLE
Interruptor De Vibración Module

### ISSUE THREAD

**Issue by DanielGGR** [tectijuana/sensores#21]

**Comment by donnygg25** [comment]
**Descripción**
El módulo de interruptor de vibración Arduino KY-002 Keyes permite la detección de golpes y vibraciones.

**KY-002 ESPECIFICACIONES**

El módulo de interruptor de vibración KY-002 consiste en un resorte de vibración conductivo y una resistencia de 10k, reaccionará a los golpes y vibraciones cerrando el circuito.

**Diagrama de conexión**

Conecte la línea de alimentación (medio) y tierra (-) a +5 y GND, respectivamente. Conecte la señal (S) al pin 3 en el Arduino.


![](http://arduinomodules.info/wp-content/uploads/Arduino_KY-002_Keyes_Vibration_switch_module_connection-diagram.png)

**Comment by DanielGGR** [comment]
# Módulo de Interruptor de vibración KY-002
### **Descripción** 📋
Arduino Vibration Switch Module KY-002 Keyes permite la detección de impactos, golpes y vibraciones.

![Módulo de vibración KY-002](https://arduinomodules.info/wp-content/uploads/KY-002_vibration_switch_arduino_module-240x240.jpg)
___
### **Especificación** 📚
El módulo de interruptor de vibración KY-002 consiste en un resorte de vibración conductor y una resistencia de 10k, reaccionará al choque y la vibración cerrando el circuito.
|Voltaje de Operación 🔋|Dimensión|   |   |   |
|---|---|---|-|---|
|⚡ 5V |18.5mm x 15mm
___
### **Funcionamiento del Módulo KY-002** ✅
El módulo KY-002 incorpora un interruptor sensible a la agitación. Tiene un resorte rodeado de material conductor. Cuando el módulo experimenta choque o vibración, el resorte flexiona y toca el material conductor circundante.
___
### **Diagrama de conexión** 🔌
![Diagrama de Conexión](https://www.phippselectronics.com/wp-content/uploads/2020/08/KY-002-article-image2.png)
___
### **Materiales necesarios para la práctica** 🗒️
1. Arduino Uno.
2. Cables de conexión.
3. Módulo de interruptor de vibración KY-002.
___
### **Código de la práctica** 🖥️
~~~
void setup() {
  pinMode(8, INPUT);   //El módulo KY-002 está conectado al pin8
  pinMode(13, OUTPUT); //Establecer el pin 13 a la salida que también es el LED.

}

void loop() {
  if(digitalRead(8) == HIGH) {  //El módulo hará el pin 8 ALTO si detecta choque / vibración
    digitalWrite(13, HIGH);     //Encender el led y establecer en alto
  }
  else digitalWrite(13, LOW);   //Apagar el led de lo contrario 
}
~~~
### **Fuentes de Consulta** 🌐
https://www.phippselectronics.com/using-the-vibration-switch-module-ky-002-with-arduino/

https://arduinomodules.info/ky-002-vibration-switch-module/

**Comment by donnygg25** [comment]
**CÓDIGO DE PRUEBA**


int Led = 13 ; // define la interfaz LED
int KY02 = 9 ; // define la interfaz del sensor de vibración 
int buzzer = 8; // define la interfaz del buzzer
int val ; // define variables numéricas val
void setup() {
pinMode ( Led , OUTPUT ) ; // define el LED como interfaz de salida
pinMode ( ky02 , INPUT ) ; // define la interfaz de salida del sensor de vibracion
pinMode ( buzzer, OUTPUT); // define la interdaz de salida del buzzer 
}
void loop()
{
val = digitalRead ( KY02 ) ; 
if ( val == HIGH )
digitalWrite ( Led , LOW ) ;
noTone(buzzer);
}
else
{
digitalWrite ( Led , HIGH ) ;
note (buzzer, 1000, 1000);
delay (500);
}
}
