### ISSUE TITLE
Módulo: de Reed

### ISSUE THREAD

**Issue by GussyDieTwice** [tectijuana/sensores#36]
# Sensor Magnetico KY-021

![imagen](https://user-images.githubusercontent.com/60414093/76579528-d2e8f100-6489-11ea-9b27-21032d5d7af5.png)
 
![imagen](https://user-images.githubusercontent.com/60414093/76579599-1c394080-648a-11ea-9b70-6d7ff7d237c6.png)

#### 
Este módulo consta de una resistencia de 10 kΩ y un pequeño interruptor de lengüeta que se encuentra normalmente abierto y se cierra cuando se expone a un campo magnético. Compatible con plataformas electrónicas como Arduino y otro tipo de microcontroladores. Estos sensores en su gran mayoría son usados para detectar la apertura de algunas puertas en gabinetes, esto en el área de las telecomunicaciones, o en sistemas mecánicos como sensores de proximidad.
####

# Funcion
####
El KY-021 contiene una resistencia de 10 kΩ y una pequeña lengüeta magnética que comúnmente es utilizado en sistemas mecánicos como sensores de proximidad o como interruptor digital magnético. Este modulo es compatible con plataformas electrónicas populares como Arduino, Teensy, Raspberry Pi y ESP8266.

Este módulo te permitirá detectar campos magnéticos de una forma rápida, fácil y eficiente, con Mini Lámina Magnética es un sensor que se encuentra comúnmente abierto y al detectar un campo magnético se cierra, permitiendo el paso del voltaje. Este módulo incluye una resistencia de 10 kΩ y no es necesario adicionar ninguna otro resistencia.
####
## ESPECIFICACIONES Y CARACTERÍSTICAS

- Tipo: Sensor Interruptor Magnetico
- Numero de modelo: KY-021
- Tipo de salida: Digital
- Altura: 21 mm
- Largo: 15 mm
- Ancho: 9 mm
- Voltaje de funcionamiento: 3.3 Volts  a 5 Volts
- Bajo consumo de energía
- Peso: 2 gr

## Diagrama de conexion.
![imagen](https://user-images.githubusercontent.com/60414093/76579583-075cad00-648a-11ea-9aa9-c762dd21df7b.png)

## Código ejemplo.
![imagen](http://cursoarduino.proserquisa.com/wp-content/uploads/2016/10/24-04.png)
En la imagen anterior vemos como el código de este sensor actúa como un botón, por lo que lo podemos programar de la misma manera ya que cuando este tenga contacto con un campo electromagnético dejara pasar la señal para que encienda el led.

**Comment by SolisLaredoPerezGerardoAlberto** [comment]
> ![imagen](https://user-images.githubusercontent.com/60414093/76579599-1c394080-648a-11ea-9b70-6d7ff7d237c6.png)
> ![imagen](https://user-images.githubusercontent.com/60414093/76579528-d2e8f100-6489-11ea-9b27-21032d5d7af5.png)
> 
> Módulo de interruptor de láminas magnéticas Arduino Keyes KY-021. Un interruptor de láminas es un sensor magnético que normalmente está abierto y se cierra cuando se expone a un campo magnético.
> 
> Especificaciones
> El mini módulo de interruptor de láminas magnético KY-021 consta de una resistencia de 10kΩ y un pequeño interruptor de láminas accionado por un campo magnético, comúnmente utilizado en sistemas mecánicos como sensores de proximidad. Compatible con plataformas electrónicas populares como Arduino, Teensy y ESP8266.
> 
> Voltaje de funcionamiento | 3.3V a 5v
> Tipo de salida | Digital
> 
> **Diagrama de conexión.**
> ![imagen](https://user-images.githubusercontent.com/60414093/76579583-075cad00-648a-11ea-9aa9-c762dd21df7b.png)

En este boceto de Arduino, leeremos los valores de las interfaces digitales y analógicas en el KY-025, necesitará un imán para interactuar con el módulo.

La interfaz digital enviará una señal ALTA cuando se detecte un campo magnético, encendiendo el LED en el Arduino (pin 13).

Por otro lado, la interfaz analógica devolverá un valor numérico ALTO cuando no hay campo magnético presente y caerá a cero cuando un imán esté cerca.

Código: 
int led = 13; // define the LED pin
int digitalPin = 3; // KY-025 digital interface
int analogPin = A0; // KY-025 analog interface
int digitalVal; // digital readings
int analogVal; //analog readings

void setup()
{
  pinMode(led, OUTPUT);
  pinMode(digitalPin, INPUT);
  //pinMode(analogPin, OUTPUT);
  Serial.begin(9600);
}

void loop()
{
  // Read the digital interface
  digitalVal = digitalRead(digitalPin); 
  if(digitalVal == HIGH) // if magnetic field is detected
  {
    digitalWrite(led, HIGH); // turn ON Arduino's LED
  }
  else
  {
    digitalWrite(led, LOW); // turn OFF Arduino's LED
  }

  // Read the analog interface
  analogVal = analogRead(analogPin); 
  Serial.println(analogVal); // print analog value to serial

  delay(100);
}

> ![imagen](https://user-images.githubusercontent.com/60414093/76579599-1c394080-648a-11ea-9b70-6d7ff7d237c6.png)
> ![imagen](https://user-images.githubusercontent.com/60414093/76579528-d2e8f100-6489-11ea-9b27-21032d5d7af5.png)
> 
> Módulo de interruptor de láminas magnéticas Arduino Keyes KY-021. Un interruptor de láminas es un sensor magnético que normalmente está abierto y se cierra cuando se expone a un campo magnético.
> 
> Especificaciones
> El mini módulo de interruptor de láminas magnético KY-021 consta de una resistencia de 10kΩ y un pequeño interruptor de láminas accionado por un campo magnético, comúnmente utilizado en sistemas mecánicos como sensores de proximidad. Compatible con plataformas electrónicas populares como Arduino, Teensy y ESP8266.
> 
> Voltaje de funcionamiento | 3.3V a 5v
> Tipo de salida | Digital
> 
> **Diagrama de conexión.**
> ![imagen](https://user-images.githubusercontent.com/60414093/76579583-075cad00-648a-11ea-9aa9-c762dd21df7b.png)
