### ISSUE TITLE
Módulo: Key Switch

### ISSUE THREAD

**Issue by Carlos-Gallardoo** [tectijuana/sensores#37]
.

**Comment by uliomar87** [comment]
# Modulo KY004 
![image](https://user-images.githubusercontent.com/60414095/76581070-578a3e00-648f-11ea-8816-a705b7349d3f.png)

MÓDULO DE INTERRUPTOR DE LLAVE ARDUINO KEYES KY-004 ES UN BOTÓN PULSADOR QUE GENERARÁ UNA SEÑAL ALTA CUANDO SE PRESIONE.

## Especificaciones 
|Clasificación | 50mA 12VC|
|--------------|--------------|
|Temperatura ambiental | -25 ° C a 105 ° C [-13 ° F a 221 ° F]|
|Eléctricamente la vida | 100,000 ciclos|
|Fuerza de operación | 180/230 (± 20 gf)|
|Dimensiones | 18.5 mm x 15 mm [0.728 pulgadas x 0.591 pulgadas]|

## DIAGRAMA DE CONEXIÓN KY-004
Conecte la línea de alimentación (centro) y masa a + 5V y GND respectivamente. Conecte la señal (S) al pin 3 en el arduino.

|KY-004 | Arduino|
|--------|----------|
|   S       | Pin 3     |
| medio | + 5V     |
|        –  | GND     |


![image](https://user-images.githubusercontent.com/60414095/76580989-067a4a00-648f-11ea-8477-580a47c1a3b9.png)
