### ISSUE TITLE
Módulo: LCD con o sin interface

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/sensores#39]
> ![Captura de pantalla 2020-03-16 a las 22 15 55](https://user-images.githubusercontent.com/2523851/76824154-7b24ef80-67d3-11ea-962a-f02fb1878c25.png)
> 
> Introducción Como todos sabemos, aunque las pantallas LCD y algunas otras enriquecen enormemente la interacción hombre-máquina, comparten una debilidad común. Cuando están conectados a un controlador, se ocuparán varias E / S del controlador que no tiene tantos puertos externos. También restringe otras funciones del controlador. Por lo tanto, LCD1602 con un puerto I2C está desarrollado para resolver el problema. También es simple de manejar. Tiene solo dos líneas de datos bidireccionales, una línea de datos en serie y una de reloj en serie.
> Cómo cablear: GND — GND; VCC — VCC; SDA — A4; SCL:
> aplicación A5 Se utiliza para mostrar caracteres, letras y números.
> Componente: 1 * I2C LCD1602
![image](https://user-images.githubusercontent.com/60403045/77720343-e37a8a80-6fa4-11ea-9469-f8e20459d730.png)
Librería para LCD 16×2 por I2C con Arduino
Para usar el LCD 16×2 por I2C con Arduino es necesario también agregar una librería a nuestro IDE, de forma que este sepa como comunicarse con el  chip PCF8574. Ya explicamos en alguna ocasión como cargar una librería y comenzar a utilizarla, si tienes dudas te recomendamos revisar el tutorial. Cabe aclarar que esta librería, así como el adaptador I2C deben funcionar de forma correcta con las pantallas de 20×4.

Puedes descargar la librería desde la página oficial en Bitbucket (repo) o desde nuestro servidor. A continuación dejamos los enlaces para cada una de las opciones.

Descarga desde página oficial (repositorio bitbucket)
Descarga desde nuestro servidor
La librería LiquidCrystal_I2C dispone de métodos similares (algunos idénticos) a los de la librería oficial.

LiquidCrystal_I2C() – Constructor de la clase, configura el hardware.
init() – Prepara el LCD para su uso.
clear() – Borra todos los caracteres de la pantalla LCD.
setCursor(col, row) – Permite mover el cursor a la posición indicada en sus parámetros.
print() – Imprime una variable o literal en la pantalla
scrollDisplayLeft() y scrollDisplayRight() – Recorre el contenido de la pantalla a la izquierda o a la derecha
backlight() y noBacklight() – Métodos para encender / apagar la iluminación de fondo
createChar(num, data) –  Crear un carácter definido por el usuario en la memoria del controlador de pantalla.

**Comment by IoTeacher** [comment]
IIC I2C TWI Serial 2004 20x4 LCD Module Shield for Arduino Uno Mega2560
earlier in 2017. The I2C interface promised a much cleaner interface than the standard one.
Well worth the price difference but initially I was at a loss to find drivers and example code to drive it.
Finially I discovered this code fragment that initializes the board. It works with version 1.1.2 of
the LiquidCrystal_I2C library by Frank de Brabander which is included in version 1.8.2 of the Arduino IDE
```

#include <Wire.h>
#include <LiquidCrystal_I2C.h>

LiquidCrystal_I2C lcd(0x27,20,4);

void setup()
{
Wire.begin();
lcd.init();
lcd.backlight();

}
```

**Comment by IoTeacher** [comment]
Color: 20x4 I2C LCDVerified Purchase
This worked perfectly when connecting to a Particle Photon. I2C Address is 0x27, and I used 5K pull-up resistors on the SDA and SCI lines. The display is nice and bright. It was seriously easy to use.

Below is the test program I used from Particle (search the Particle.IO library for LiquidCrystal_I2C_Spark.h":

```
/*
8-Feb-2015
Jim Brower
bulldoglowell@gmail.com
*/

#include "LiquidCrystal_I2C_Spark.h"

LiquidCrystal_I2C *lcd;

int lastSecond = 0;

void setup(void)
{
Serial.begin(9600);
lcd = new LiquidCrystal_I2C(0x27, 16, 4);
lcd->init();
lcd->backlight();
lcd->clear();
lcd->print("***Spark Time***");
}

void loop(void)
{
if (Time.second() != lastSecond)
{
Serial.print(Time.timeStr());
lcd->setCursor(0,1);
lcd->print(Time.hour() < 10? " 0" : " ");
lcd->print(Time.hour());
lcd->print(Time.minute() < 10? ":0": ":");
lcd->print(Time.minute());
lcd->print(Time.second() < 10? ":0": ":");
lcd->print(Time.second());
lastSecond = Time.second();
}
}
```

**Comment by IoTeacher** [comment]
https://www.amazon.com/JANSANE-Arduino-Display-Interface-Raspberry/dp/B07D83DY17/ref=pd_sbs_147_1/139-4088737-5596051?_encoding=UTF8&pd_rd_i=B07D83DY17&pd_rd_r=4e5851a1-0890-4316-a73d-ce5943294e26&pd_rd_w=KsYB1&pd_rd_wg=8fcPh&pf_rd_p=7cd8f929-4345-4bf2-a554-7d7588b3dd5f&pf_rd_r=6JAEPD3S9E50KZM3W7CT&refRID=6JAEPD3S9E50KZM3W7CT&th=1

**Comment by SolisLaredoPerezGerardoAlberto** [comment]
> ![Captura de pantalla 2020-03-16 a las 22 15 55](https://user-images.githubusercontent.com/2523851/76824154-7b24ef80-67d3-11ea-962a-f02fb1878c25.png)
> 
> Introducción Como todos sabemos, aunque las pantallas LCD y algunas otras enriquecen enormemente la interacción hombre-máquina, comparten una debilidad común. Cuando están conectados a un controlador, se ocuparán varias E / S del controlador que no tiene tantos puertos externos. También restringe otras funciones del controlador. Por lo tanto, LCD1602 con un puerto I2C está desarrollado para resolver el problema. También es simple de manejar. Tiene solo dos líneas de datos bidireccionales, una línea de datos en serie y una de reloj en serie.
> Cómo cablear: GND — GND; VCC — VCC; SDA — A4; SCL:
> aplicación A5 Se utiliza para mostrar caracteres, letras y números.
> Componente: 1 * I2C LCD1602
![image](https://user-images.githubusercontent.com/60403045/77720343-e37a8a80-6fa4-11ea-9469-f8e20459d730.png)
Librería para LCD 16×2 por I2C con Arduino
Para usar el LCD 16×2 por I2C con Arduino es necesario también agregar una librería a nuestro IDE, de forma que este sepa como comunicarse con el  chip PCF8574. Ya explicamos en alguna ocasión como cargar una librería y comenzar a utilizarla, si tienes dudas te recomendamos revisar el tutorial. Cabe aclarar que esta librería, así como el adaptador I2C deben funcionar de forma correcta con las pantallas de 20×4.

Puedes descargar la librería desde la página oficial en Bitbucket (repo) o desde nuestro servidor. A continuación dejamos los enlaces para cada una de las opciones.

Descarga desde página oficial (repositorio bitbucket)
Descarga desde nuestro servidor
La librería LiquidCrystal_I2C dispone de métodos similares (algunos idénticos) a los de la librería oficial.

LiquidCrystal_I2C() – Constructor de la clase, configura el hardware.
init() – Prepara el LCD para su uso.
clear() – Borra todos los caracteres de la pantalla LCD.
setCursor(col, row) – Permite mover el cursor a la posición indicada en sus parámetros.
print() – Imprime una variable o literal en la pantalla
scrollDisplayLeft() y scrollDisplayRight() – Recorre el contenido de la pantalla a la izquierda o a la derecha
backlight() y noBacklight() – Métodos para encender / apagar la iluminación de fondo
createChar(num, data) –  Crear un carácter definido por el usuario en la memoria del controlador de pantalla.

**Comment by IoTeacher** [comment]
![Screen Shot 2020-03-29 at 16 04 53](https://user-images.githubusercontent.com/2523851/77863400-f1afed00-71d6-11ea-814b-3bbc39e8ac7f.png)


[LCDRS2.pdf](https://github.com/tectijuana/sensores/files/4400057/LCDRS2.pdf)

**Comment by IoTeacher** [comment]
[LCDRS2.pdf](https://github.com/tectijuana/sensores/files/4400044/LCDRS2.pdf)
