### ISSUE TITLE
Módulo: magnético de clase Bihor

### ISSUE THREAD

**Issue by moises945** [tectijuana/sensores#42]
SENSOR MAGNÉTICO CLASE BIHOR (KY-035)
Código PPD-0097

Este es un módulo de sensor de campo magnético analógico. La fuerza del campo viene dada por una tensión analógica en el terminal de señal del módulo de KY-035.

**Comment by IoTeacher** [comment]
``Codigo``

**Comment by everthx** [comment]
[FERNANDO LUNA FUENTES - B2_ Presentación de sensores o módulos.pdf](https://github.com/tectijuana/sensores/files/4384228/FERNANDO.LUNA.FUENTES.-.B2_.Presentacion.de.sensores.o.modulos.pdf)
Enviando Expo
