### ISSUE TITLE
Sensor LIDAR

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/sensores#45]

**Comment by Fernandoov21** [comment]
**¿Qué es el sensor LIDAR?**
La tecnología LIDAR es un sistema que permite la medición precisa de distancias emitiendo pulsos de luz (invisibles al ojo humano). Dispara una pulsación de luz, mide el tiempo que tarda en llegar rebotado al iPhone y lo manda a un procesador. Allí se interpretan los datos de una nube de puntos generada a partir de los diferentes disparos realizados por el LIDAR para conocer con exactitud la distancia a un plano u objeto. 

El LIDAR es uno de los sensores de cabecera de algunos vehículos de exploración espacial que tienen que viajar sobre superficies como la del planeta Marte o en cortacésped autónomos para medir distancias.


**Caracteristicas:** 

- Modelo ALS60 de Leica Geosystems.
- Láser en la banda espectral NIR (1.064 nm).
- Frecuencia de pulso: 200 Khz.
- Frecuencia de escaneo: 100 Hz.
- FOV: hasta 75º
- Permite capturar hasta 4 retornos por pulso.
- Canal de intensidad de 8 bits.

**Código fuente:**

// Include Libraries
#include "Arduino.h"
#include "LIDARLite.h"
#include "Wire.h"


// Pin Definitions



// Global variables and defines

// object initialization
LIDARLite lidarLite;


// define vars for testing menu
const int timeout = 10000;       //define timeout of 10 sec
char menuOption = 0;
long time0;

// Setup the essentials for your circuit to work. It runs first every time your circuit is powered with electricity.
void setup() 
{
    // Setup Serial which is useful for debugging
    // Use the Serial Monitor to view printed messages
    Serial.begin(9600);
    while (!Serial) ; // wait for serial port to connect. Needed for native USB
    Serial.println("start");
    
    lidarLite.begin(0, true); // Set configuration to default '0', change this number to try out alternate configurations. I2C speed set to 400 kHz.
    menuOption = menu();
    
}

// Main logic of your circuit. It defines the interaction between the components you selected. After setup, it runs over and over again, in an eternal loop.
void loop() 
{
    
    
    if(menuOption == '1') {
    // LIDAR-Lite v3 - Test Code
    // Take a measurement with receiver bias correction and print to serial terminal
    int lidarLiteDist = lidarLite.distance();
    Serial.print(lidarLiteDist);
    Serial.println(" [cm]");
    delay(50);
    }
    
    if (millis() - time0 > timeout)
    {
        menuOption = menu();
    }
    
}



// Menu function for selecting the components to be tested
// Follow serial monitor for instrcutions
char menu()
{

    Serial.println(F("\nWhich component would you like to test?"));
    Serial.println(F("(1) LIDAR-Lite v3"));
    Serial.println(F("(menu) send anything else or press on board reset button\n"));
    while (!Serial.available());

    // Read data from serial monitor if received
    while (Serial.available()) 
    {
        char c = Serial.read();
        if (isAlphaNumeric(c)) 
        {   
            
            if(c == '1') 
    			Serial.println(F("Now Testing LIDAR-Lite v3"));
            else
            {
                Serial.println(F("illegal input!"));
                return 0;
            }
            time0 = millis();
            return c;
        }
    }
}
