### ISSUE TITLE
Sensor infrarojos

### ISSUE THREAD

**Issue by DianaHFer** [tectijuana/sensores#65]

**Comment by DianaHFer** [comment]
### SENSOR INFRAROJO.
Dispositivo electrónico/mecánico/químico que mapea un atributo ambiental resultando una medida cuantizada, normalmente un nivel de tensión eléctrica. Particularmente, el sensor infrarrojo es un dispositivo electrónico capaz de medir la radiación electromagnética infrarroja de los cuerpos en su campo de visión.


![image](https://user-images.githubusercontent.com/71353266/117513920-9444ae80-af47-11eb-8c6b-eb975b9ae363.png)
```
// C++ code
//
int sensor = 0;

void setup()
{
  pinMode(2, INPUT);
  pinMode(9, OUTPUT);
}

void loop()
{
  sensor = digitalRead(2);
  if (sensor == HIGH) {
    digitalWrite(9, HIGH);
  } else {
    digitalWrite(9, LOW);
  }
  delay(10); // Delay a little bit to improve simulation performance
}
```

**Comment by CesarAm233** [comment]
[![Sensor-Infra-Red.png](https://i.postimg.cc/CLvsHbZJ/Sensor-Infra-Red.png)](https://postimg.cc/0bwS9M0J)

Un detector infrarrojo es un tipo de dispositivo que tiene la capacidad de medir la radiación electromagnética infrarroja que emiten los cuerpos que se encuentran dentro de su campo de visión. Se trata de un tipo de radiación que emiten todos los cuerpos de forma independiente a que exista otro tipo de luz ambiental. De este modo, permite observar espacios y objetos sin necesidad de que exista luz visible o de otro tipo en el entorno.

![Diagrama-del-Sensor-Infrarrojo.png](https://i.postimg.cc/cL45ds3k/Diagrama-del-Sensor-Infrarrojo.png)

```python
#include <IRremote.h>
#define pinSensorIR 11

IRrecv sensorIR(pinSensorIR) ;
decode_results codigoIR;

void setup() {
	Serial.begin(9600);
	sensorIR.enableIRIn();
}

void loop () {
	if (sensorIR.decode(&codigoIR)) {
		Serial.println(codigoIR.value,HEX);
		sensorIR.resume () ;
	}
	delay (100);
}
```

**Comment by IoTeacher** [comment]
Pueden ser tan amables de mover el codigo a CircuitPython
