### ISSUE TITLE
KY-039 Heartbeat

### ISSUE THREAD

**Issue by DanielAquinoIng** [tectijuana/sensores#82]
![Cool Text - Heartbeat](https://user-images.githubusercontent.com/84552885/144182347-d85d39e7-cc3d-405d-9155-542a6a742660.png)
![Sensor](https://user-images.githubusercontent.com/84552885/144518236-99b46ddd-8424-484c-a571-a5388afdd4f6.jpg)

## Sensor: KY-039 Heartbeat

**Comment by DanielAquinoIng** [comment]
# Marco teórico

### ¿Qué es el Detector de Ritmo Cardíaco? 💓

El Detector de Ritmo Cardíaco KY-039 es un sensor óptico de pulsos cardíacos por medio de la huella digital utiliza un LED infrarrojo brillante (IR) y un fototransistor para detectar el pulso del dedo, un LED rojo flashea con cada pulso.

Es un dispositivo de “Plug and Play”, puede ser utilizado para obtener fácilmente una lectura del ritmo cardíaco en tiempo real. 

### ¿Para que funciona el KY-039? 🤔
El KY-039 es una alternativa económica para medir el ritmo cardiaco y es compatible con diversas tarjetas de desarrollo como Arduino, Raspberry, ESP82, entre otras.


### ¿Cómo funciona el sensor de pulso cardíaco? 👷🏻‍♂️
El monitor de pulso funciona de la siguiente manera: el LED es el lado luminoso del dedo y el fototransistor del otro lado del dedo, el fototransistor utilizado para obtener el flujo emitido, cuando la presión sanguínea pulsa con el dedo cuando la resistencia del fototransistor ser ligeramente cambiado.

Cuando el pulso de la presión arterial pasa por el dedo la corriente de la base del fototransistor se modifica ligeramente, debido a que la cantidad de luz que puede atravesar el dedo disminuye, lo que significa una salida por el puerto análogo diferente.

Es muy importante tener en cuenta que es prioritario que se mantenga lo más alejado de la luz parásita, es decir de la luz externa por ejemplo la iluminación del hogar, por eso se recomienda usar algún sistema que sirva de escudo al fototransistor y que evite que otra luz diferente a la del led llegue ya que la señal del latido del corazón es muy débil y la luz ambiente añadirá un ruido considerable.

**Comment by DanielAquinoIng** [comment]
# Ficha técnica

![especificaciones2](https://user-images.githubusercontent.com/84552885/144528044-c6614b33-9539-4ea0-94e0-90f8653f49fa.png)

### ESPECIFICACIONES TÉCNICAS. 🛠️
- Modelo: KY-039
- Voltaje: 3.3V a 5 V
- Tipo de Salida: Analógica
- Peso: 4 g
- Dimensiones: 25mm x 12mm x 12 mm


Este modulo tiene tres pins: GND, Vcc+ y Signal. El pinout es el siguiente:
![pinout](https://user-images.githubusercontent.com/84552885/144520684-b4e05b62-5744-4e6f-b4cc-1fb168c87ea8.jpg)


El esquema del sensor de latido KY-039 es el siguiente:
![esquema](https://user-images.githubusercontent.com/84552885/144524203-ce1c1c5a-6114-4392-82a1-ada1da1588a7.jpg)
https://www.thegeekpub.com/wp-content/uploads/2019/07/KY-039-heartbeat-sensor-schematic.jpg

**Comment by DanielAquinoIng** [comment]
## Modo de conexión 

| Pico   | KY-039 Heartbeat |
|--------|------------------|
| Pin 38 | GND              |
| Pin 36 | 3.3V a 5V        |
| Pin 26 | Señal analógica  |

# Diagrama

![264260970_5278392752178047_8452575502907336098_n](https://user-images.githubusercontent.com/84552885/145543133-c584788d-91d3-4870-b0ab-26d34bb96813.png)


## Sensor y salidas: 
![especificaciones](https://user-images.githubusercontent.com/84552885/144535290-da95c082-2b38-4ca0-ba67-40b458e6e175.jpg)

**Comment by DanielAquinoIng** [comment]
# Código
```python
# Aquino Villegas Daniel 18212144
from machine import ADC
from utime import sleep

sensor = ADC(26)

conversion_factor = 3.3 / (65535)

while True:
        lectura = sensor.read_u16() * conversion_factor
	print(lectura)
        sleep(0.09)
```

**Comment by Rulas-Boy** [comment]
@DanielAquinoIng 
La razon por la que no despliega nada es porque la condicion de la linea 43 nunca se va a cumplir puesto que ambos valores incrementan igual conforme el ciclo itera.

Creo que hay algo que no deberia estar dentro del ciclo infinito.

![Screenshot from 2021-12-09 20-11-01](https://user-images.githubusercontent.com/71353362/145516100-51e72b66-7125-45c6-831a-7d5e79ef52a1.png)
