### ISSUE TITLE
KY-010 Light Blocking

### ISSUE THREAD

**Issue by alfredo70fil** [tectijuana/sensores#89]

**Comment by SalasJ13** [comment]
Marco teorico.

**Comment by SalasJ13** [comment]
### Marco Teorico

**Comment by SalasTec13** [comment]
#Marco teórico.
#Diagramas y tablas técnicas.
#Código
#Ejecución o comprobación.

**Comment by SalasJ13** [comment]
### 🅺🆈-010 𝕊𝕖𝕟𝕤𝕠𝕣 𝕕𝕖 𝕓𝕝𝕠𝕢𝕦𝕖𝕠 𝕕𝕖 𝕝𝕦𝕫 𝕣𝕠𝕥𝕒

**Comment by SalasTec13** [comment]
### 🅺🆈-010 🆂🅴🅽🆂🅾🆁 🅳🅴 🅱🅻🅾🆀🆄🅴🅾 🅳🅴 🅻🆄🆉 🆁🅾🆃🅰

**Comment by SalasTec13** [comment]
![Alt text](https://drive.google.com/file/d/1XYxbK6YvwHypHZnuVVYKxloV5od5pLEP/view?usp=sharing "a title")

**Comment by SalasTec13** [comment]
### [KY-010] Sensor de bloqueo de luz rota

**Comment by SalasTec13** [comment]
###**Marco Teórico.**

**Comment by SalasTec13** [comment]
![titulo-removebg-preview](https://user-images.githubusercontent.com/89493294/144682289-83ec28b4-b87f-4ffe-9e91-e3e49e4ca991.png)

**Comment by SalasTec13** [comment]
### **Marco Teórico**
EL ky-010 es un fotosensor que combina dos partes las cuales son transmisión y de recepción en un módulo, ya que de un lado tiene el emisor y por el otro extremo tiene un rector que recibe la señal y manda una señal cuando se interrumpe la luz infrarroja y manda una señal al microcontrolador.

**Comment by SalasTec13** [comment]
### `2. Diagrama`

**Comment by SalasTec13** [comment]
### `3.  Código`

# Los módulos necesarios serán importados y configurados
importar RPi.GPIO como GPIO
tiempo de importación
  
GPIO.setmode (GPIO.BCM)
  
# El pin de entrada que está conectado con el sensor
GPIO_PIN = 21
Configuración de GPIO (GPIO_PIN, GPIO.IN, pull_up_down = GPIO.PUD_DOWN)
  
imprimir "Prueba del sensor KY-010 [presione ctrl + c para finalizar la prueba]"
  
def función de salida (nulo):
         imprimir ("El sensor está bloqueado")
  
# detección de señal (flanco ascendente).
GPIO.add_event_detect (GPIO_PIN, GPIO.RISING, callback = outputFunction, tiempo de rebote = 100)
  
# Bucle del programa principal
tratar:
         mientras que es cierto:
                 hora de dormir (1)
  
# Trabajo de recolección de residuos una vez finalizado el programa
excepto KeyboardInterrupt:
         GPIO.cleanup ()

**Comment by SalasJ13** [comment]
![titulo-removebg-preview (1)](https://user-images.githubusercontent.com/89493294/144682432-e709be06-c991-48fb-a8c5-4205b8295e32.png)

**Comment by SalasTec13** [comment]
![titulo-removebg-preview (1)](https://user-images.githubusercontent.com/89493294/144682432-e709be06-c991-48fb-a8c5-4205b8295e32.png)

**Comment by SalasTec13** [comment]
### `1. Marco Teórico`

El módulo KY-010  consta de un emisor / detector óptico en la parte frontal y dos resistencias (1 kΩ y 33 Ω) en la parte posterior. 
Es un fotosensor que combina dos partes las cuales son transmisión y de recepción en un módulo, ya que de un lado tiene el emisor y por el otro extremo tiene un rector que recibe la señal y cuando se interrumpe la luz infrarroja esta manda una señal al microcontrolador. 

> ¿Para qué es?

Se utilizan para detectar la velocidad de un giro de un motor con un una lamida también puede detectar cualquier objeto que interrumpa la luz infrarroja se puede utilizar para el cierre de una puerta con una sencilla programación y para algunos desplazamientos de máquinas.

> ¿Cómo Funciona?

El sensor ky-010 es un dispositivo electrónico que responde cuando se interrumpe la luz infrarroja el cual se manda al microcontrolador la señal se emplean en algunas aplicaciones como pueden ser en la automatización de oficinas, árcades, detección de objetos en general.

![KY-010](https://user-images.githubusercontent.com/89493294/144683140-520dd8b6-3899-4c82-9bc9-454340db3150.jpg)

**Comment by SalasTec13** [comment]
### `2. Diagrama`

![pi-and-ky-010-layout](https://user-images.githubusercontent.com/89493294/144686932-a7214c04-93d0-4a5b-bdfa-f63ba80bb3b4.jpg)



> Especificaciones Técnicas.
- Voltaje de funcionamiento 3.3 ~ 5V.
- Dimensiones 18.5mm x 15mm [0.728in x 0.591in]

> Diagrama de conexión KY-010.
![pi-and-ky-010-schematic](https://user-images.githubusercontent.com/89493294/144686912-9e4286bc-89e5-4e97-93c5-85b3a3b58184.jpg)


> Conexiones.

| KY-010    	| Rasperry        	|
|-----------	|-----------------	|
| (-)       	| (Izquierda) GND 	|
| Pin medio 	| + 5V            	|
| (S)       	| (Derecha) Pin 3 	|

**Comment by SalasTec13** [comment]
### `3. Codigo`

``` python
# Los módulos necesarios serán importados y configurados

import RPi.GPIO as GPIO
import time
  
GPIO.setmode(GPIO.BCM)
  
# El pin de entrada que está conectado con el sensor

GPIO_PIN = 21
GPIO.setup(GPIO_PIN, GPIO.IN, pull_up_down = GPIO.PUD_DOWN)
  
print "KY-010 Sensor Test [press ctrl+c to end the test]"
  
def outputFunction(null):
        print("Sensor is blocked")
  
# detección de señal (flanco ascendente).

GPIO.add_event_detect(GPIO_PIN, GPIO.RISING, callback=outputFunction, bouncetime=100) 
  
# Bucle del programa principal

try:
        while True:
                time.sleep(1)
  
# Trabajo de recolección de residuos una vez finalizado el programa

except KeyboardInterrupt:
        GPIO.cleanup()
```

**Comment by IoTeacher** [comment]
SE sube el cooltext por errores..
[borrame.pdf](https://github.com/tectijuana/sensores/files/8219503/borrame.pdf)

.
