### ISSUE TITLE
KY-023 Joystick

### ISSUE THREAD

**Issue by Rulas-Boy** [tectijuana/sensores#92]
![Cool Text - JOYSTICK 399252203092064](https://user-images.githubusercontent.com/79487256/144521169-1661385c-64da-41f0-ba86-8492cb158654.png)

**Comment by SilverioAmaro** [comment]
![Cool Text - JOYSTICK 399252203092064](https://user-images.githubusercontent.com/79487256/144521058-d43a01da-c2d3-4d03-a488-1959df885e5d.png)

**Comment by SilverioAmaro** [comment]
## Tablas técnicas

| ESPECIFICACIÓN Y CARACTERÍSTICAS |
| :--- |
| Módulo: JoyStick biaxial XY (KY-023) |
| Voltaje de alimentación: 3.3 V a 5V |
| Salida: Analógica(X,Y) y Digital(Z) |
| Número de potenciómetros: 2 de 10Kohm. |
| Pulsador central normalmente abierto. |
| Dimensiones: 40mm x 26mm  x 32 mm |
| Peso: 14 g |
